import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { headers } from "next/headers";
import { useHtmlContext } from "next/dist/shared/lib/html-context.shared-runtime";
import AskHelpButton from "@/components/AskHelpButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ params, children }) {
  const heads = headers();
  const pathName = heads.get("next-pathname ");
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <AskHelpButton />
      </body>
    </html>
  );
}
